import { useState } from 'react'
import { RefreshCw, CheckCircle2, AlertCircle, Sparkles, Copy, ThumbsUp, Clock } from 'lucide-react'
import { feedbackAPI } from '../api/client'
import { useApi, LoadingSpinner, ApiError } from '../hooks/useApi'
import { SentimentBadge, ProgressBar, ConfidenceRing, MiniMetric } from '../components/UI'

export default function ResponseGeneration() {
  // Fetch all feedback for the queue (admin) or own feedback
  const { data, loading, error, refetch } = useApi(() => feedbackAPI.allFeedback({ size: 20 }))
  const [selectedId, setSelectedId] = useState(null)
  const [copied, setCopied] = useState(false)
  const [approving, setApproving] = useState(false)
  const [regenerating, setRegenerating] = useState(false)
  const [localData, setLocalData] = useState(null)  // overrides after approve/regen

  if (loading) return <LoadingSpinner message="Loading feedback queue…" />
  if (error)   return <div className="p-6"><ApiError error={error} onRetry={refetch} /></div>

  const items = localData?.items || data?.items || []
  if (!items.length) return (
    <div className="p-6 flex flex-col items-center justify-center py-20 text-slate-500">
      No feedback in queue yet. Submit some feedback first.
    </div>
  )

  const activeId = selectedId || items[0]?.id
  const selected = items.find(f => f.id === activeId) || items[0]

  const handleCopy = () => {
    navigator.clipboard.writeText(selected?.generated_response || '')
    setCopied(true); setTimeout(() => setCopied(false), 2000)
  }

  const handleApprove = async () => {
    setApproving(true)
    try {
      const res = await feedbackAPI.approve(selected.id)
      // Update local state
      const updated = items.map(i => i.id === selected.id ? res.data : i)
      setLocalData({ items: updated })
    } catch(e) { console.error(e) }
    finally { setApproving(false) }
  }

  const handleRegenerate = async () => {
    setRegenerating(true)
    try {
      const res = await feedbackAPI.regenerate(selected.id)
      const updated = items.map(i => i.id === selected.id ? res.data : i)
      setLocalData({ items: updated })
    } catch(e) { console.error(e) }
    finally { setRegenerating(false) }
  }

  return (
    <div className="p-6 animate-fade-in">
      <div className="mb-6 flex items-start justify-between">
        <div>
          <h1 className="font-display text-2xl font-bold text-white tracking-tight">Response Generation</h1>
          <p className="text-sm text-slate-500 mt-1">
            Live feedback queue · Generated by your AI pipeline · Stored in <span className="font-mono text-brand-400">feedbacks</span> table
          </p>
        </div>
        <button onClick={refetch} className="btn-ghost text-xs"><RefreshCw size={13}/> Refresh</button>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-5 gap-6">
        {/* Queue */}
        <div className="xl:col-span-2 space-y-2">
          <div className="label mb-3">Feedback Queue ({items.length})</div>
          {items.map(fb => (
            <button key={fb.id} onClick={() => setSelectedId(fb.id)}
              className={`w-full text-left p-4 rounded-xl border transition-all duration-200 ${
                activeId === fb.id ? 'bg-surface-700 border-brand-600/30 shadow-glow-blue/20' : 'bg-surface-800/50 border-white/5 hover:bg-surface-700/50'
              }`}>
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-mono text-brand-400">#{fb.id}</span>
                  <SentimentBadge sentiment={fb.sentiment} />
                </div>
                {fb.approval_status === 'auto' || fb.approval_status === 'approved' ? (
                  <div className="flex items-center gap-1 text-[10px] text-accent-green"><CheckCircle2 size={11}/><span>Auto</span></div>
                ) : (
                  <div className="flex items-center gap-1 text-[10px] text-accent-amber"><AlertCircle size={11}/><span>Review</span></div>
                )}
              </div>
              <p className="text-xs text-slate-400 line-clamp-2 mb-2">{fb.text}</p>
              <div className="flex items-center justify-between">
                <span className="text-[11px] text-slate-600 bg-surface-600/50 px-2 py-0.5 rounded-md">{fb.detected_topic || 'Unknown'}</span>
                <div className="flex items-center gap-1 text-[10px] text-slate-600">
                  <Clock size={10}/>{new Date(fb.created_at).toLocaleTimeString()}
                </div>
              </div>
            </button>
          ))}
        </div>

        {/* Detail — ALL data from DB */}
        {selected && (
          <div className="xl:col-span-3 space-y-4">
            <div className="card p-5">
              <div className="flex items-start justify-between mb-3">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-sm font-mono font-medium text-brand-400">#{selected.id}</span>
                    <span className="text-[11px] text-slate-600">{selected.language}</span>
                    <span className="text-[11px] text-slate-600">·</span>
                    <span className="text-[11px] text-slate-600">{selected.product_category || 'No category'}</span>
                  </div>
                  <p className="text-sm text-slate-200 leading-relaxed">{selected.text}</p>
                </div>
              </div>
              <div className="flex items-center gap-4 pt-3 border-t border-white/5">
                <ConfidenceRing value={selected.sentiment_conf || 0} size={72} label="Sentiment Conf"
                  color={selected.sentiment === 'negative' ? '#f87171' : selected.sentiment === 'positive' ? '#34d399' : '#64748b'} />
                <div className="flex-1">
                  <SentimentBadge sentiment={selected.sentiment} />
                  <div className="mt-2 text-xs text-slate-500">
                    Classified by <span className="font-mono text-brand-400">sentiment_model.pkl</span>
                  </div>
                  <ProgressBar value={selected.sentiment_conf || 0}
                    color={selected.sentiment === 'negative' ? '#f87171' : '#34d399'}
                    showPct className="mt-2" />
                </div>
              </div>
            </div>

            <div className="card p-5">
              <div className="label mb-3">Topic Prediction</div>
              <div className="flex items-center justify-between mb-3">
                <div className="text-base font-display font-bold text-white">{selected.detected_topic || 'Unknown'}</div>
                <span className="text-sm font-mono text-accent-cyan">{(selected.topic_probability || 0).toFixed(1)}%</span>
              </div>
              <ProgressBar value={selected.topic_probability || 0} color="#22d3ee" showPct />
              {selected.topic_keywords?.length > 0 && (
                <div className="mt-3">
                  <div className="label mb-2">Context Keywords (from feedbacks.topic_keywords)</div>
                  <div className="flex flex-wrap gap-1.5">
                    {selected.topic_keywords.map(k => <span key={k} className="keyword-tag">{k}</span>)}
                  </div>
                </div>
              )}
            </div>

            <div className="card p-5">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                  <Sparkles size={15} className="text-brand-400" />
                  <span className="section-title">AI-Generated Response</span>
                </div>
                {selected.approval_status === 'auto' || selected.approval_status === 'approved' ? (
                  <div className="flex items-center gap-1.5 px-2.5 py-1 bg-accent-green/10 border border-accent-green/20 rounded-lg">
                    <CheckCircle2 size={11} className="text-accent-green"/>
                    <span className="text-[11px] text-accent-green">
                      {selected.approval_status === 'approved' ? 'Approved' : 'Auto Approved'}
                    </span>
                  </div>
                ) : (
                  <div className="flex items-center gap-1.5 px-2.5 py-1 bg-accent-amber/10 border border-accent-amber/20 rounded-lg">
                    <AlertCircle size={11} className="text-accent-amber"/>
                    <span className="text-[11px] text-accent-amber">Needs Review</span>
                  </div>
                )}
              </div>
              <div className="p-4 bg-surface-700/40 rounded-xl border border-white/5 mb-4">
                <p className="text-sm text-slate-300 leading-relaxed">
                  {selected.approved_response || selected.generated_response || 'No response generated'}
                </p>
              </div>
              <div className="text-[11px] text-slate-600 mb-3">
                Stored in <span className="font-mono text-brand-400">feedbacks.generated_response</span> column
              </div>
              <div className="flex gap-2">
                <button onClick={handleRegenerate} disabled={regenerating}
                  className="btn-primary flex-1 justify-center text-xs py-2 disabled:opacity-50">
                  {regenerating ? <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin"/> : <RefreshCw size={13}/>}
                  Regenerate
                </button>
                <button onClick={handleCopy} className="btn-secondary text-xs py-2 px-3">
                  {copied ? <ThumbsUp size={13} className="text-accent-green"/> : <Copy size={13}/>}
                </button>
                {(selected.approval_status === 'needs_review') && (
                  <button onClick={handleApprove} disabled={approving}
                    className="btn-secondary text-xs py-2 px-3 text-accent-green border-accent-green/20 hover:bg-accent-green/10 disabled:opacity-50">
                    <CheckCircle2 size={13}/> Approve
                  </button>
                )}
              </div>
            </div>

            <div className="card p-5">
              <div className="label mb-3">Evaluation Metrics (from DB)</div>
              <div className="grid grid-cols-4 gap-3">
                <MiniMetric label="BLEU"       value={selected.bleu_score      ? selected.bleu_score.toFixed(3)      : '—'} color="#22d3ee"/>
                <MiniMetric label="ROUGE-L"    value={selected.rouge_l_score   ? selected.rouge_l_score.toFixed(3)   : '—'} color="#34d399"/>
                <MiniMetric label="Semantic"   value={selected.semantic_similarity ? `${selected.semantic_similarity.toFixed(1)}%` : '—'} color="#a78bfa"/>
                <MiniMetric label="Confidence" value={selected.model_confidence ? `${selected.model_confidence.toFixed(1)}%` : '—'} color="#fbbf24"/>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
